services:
  provider-relay:
    image: provider-relay:latest
    container_name: provider-relay
    restart: always
    ports:
      - 3000:3000
    environment:
      - TZ=Asia/Shanghai
      - LISTEN_PORT=3000
    volumes:
      - ./data:/app/data
networks:
  default:
    external: true
    name: prelay
