services:
  prelay-server:
    image: ghcr.io/zoranner/prelay-server:0.1.5
    container_name: prelay
    restart: always
    env_file:
      - .env
    environment:
      - PRELAY_CATALOG_DIR=/app/config/catalog
    ports:
      - 18080:18080
    volumes:
      - ./app/config/catalog:/app/config/catalog:ro
      - ./app/updates:/app/updates
      - ./data:/app/data
  postgres:
    image: postgres:16
    container_name: prelay-postgres
    restart: always
    stop_signal: SIGINT
    environment:
      - POSTGRES_DB=prelay
      - POSTGRES_USER=prelay
      - POSTGRES_PASSWORD=prelay
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U prelay -d prelay'"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 3s
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
networks:
  default:
    external: true
    name: prelay
