services:
  prelay-server:
    image: ghcr.io/zoranner/prelay-server:0.1.0
    container_name: prelay-server
    restart: always
    env_file:
      - .env
    ports:
      - "18080:18080"
    volumes:
      - ./app/config:/app/config:ro
      - ./data:/app/data
      - ./updates:/app/updates
networks:
  default:
    external: true
    name: prelay
